"use strict";
const axios = require ("axios");
const apikey = "T3n4NKFlp0ZXLogWAyWbOaij4ogMSW1H"; // your api key to the api generated by the website

const getWeather = location => {
    var keys = {"Paris":"623","London":"328328","New York":"349727"};
        // Paris key: 623
        // London key: 328328
        // New York key: 349727
    var key = keys[location];
    return new Promise ( async ( resolve , reject ) => {
        try {
            const weatherConditions = await axios.get("http://dataservice.accuweather.com/currentconditions/v1/"+key+"?apikey="+apikey+"&language=en");
            
            resolve (weatherConditions.data[0].Temperature.Metric.Value + " °C") // returns back the results to the chatbot
        }
        catch(error) {
            reject (error) ;
        }
    }) ;
 }

 module.exports = getWeather ;
